### ISSUE TITLE
Problem: Expectation for an event store: add  "Read in Order"  

### ISSUE THREAD

**Issue by ylorph** [ylorph/RandomThoughts#2]
See  PR #1 for the reason 

https://github.com/ylorph/RandomThoughts/blob/master/2019.08.09_expectations_for_an_event_store.md

https://github.com/ylorph/RandomThoughts/compare/master...add-Read-in-Order

**Comment by bartelink** [comment]
I added some comments regarding some of the changes this against the commit rather than the PR, as I had intended at https://github.com/ylorph/RandomThoughts/commit/7c6c703de7743caf52976a7ee28e27ec2fdcf3d0

TL;DR - suggesting providing some tiering of the 'requirements' such that someone with less knowledge of the tradeoffs can form an opinion about what you lose esp when building on stores that fundamentally can't deliver some guarantees
